### ISSUE TITLE
About color correction

### ISSUE THREAD

**Issue by hsiaoyi0504** [banterle/HDR_Toolbox#11]
I find there are few kinds color correction method in the source code
But I find that for ColorCorrectionMantiuk.m and ColorCorrection.m(It's schlick's method, right?), the implementation are odd, it should need HDR and LDR(tonemapped HDR) image as input, but seems it only take LDR and have manipulation for it.

**Comment by banterle** [comment]
What do you mean with odd?

They work with both LDR and HDR images. Can you clarify this please?

**Comment by hsiaoyi0504** [comment]
I mean, for color correction, it should compare the result of tonemapped (that is,LDR) with HDR, right?
But the I/O of this two function only need 1 input image, different from that for ColorCorrectionPouli

**Comment by banterle** [comment]
This is because those two techniques do not require to use the input HDR luminance.

ColorCorrectionPouli needs the original HDR for doing the correction.

**Comment by hsiaoyi0504** [comment]
No, I don't think so.
I check the paper
They correct the tonemapped image by using the ratio of before tonemapping
In Mantiuk's paper, he specific said they equal the ratio before and after tonemapping
And he mentioned the method of schlick, too

**Comment by banterle** [comment]
In the current toolbox implementation, there is only the linear chroma manipulation. This can be applied
as the Schlick's adjustment WITHOUT the input HDR image because it modifies only the color information without modifying luminance.

What you describe is the full technique which requires the TMO as well that has to be global.

I will rephrase the documentation in a better way to avoid misunderstandings.

**Comment by banterle** [comment]
I improved the documentation and changed the name of the technique in order to avoid misunderstanding (dev branch). The full technique is in the to-do list. The issue is now close.
