### ISSUE TITLE
fail to convert HDR10 to SDR with hable tone mapping 

### ISSUE THREAD

**Issue by zhengwen-zhang** [banterle/HDR_Toolbox#43]
hello, this HDR tool box is so helpful for HDR learning. Now I try to convert HDR10 to SDR but get strange color for converted SDR，the color seems no difference between converted SDR and HDR but the bitdepth is changed to 8bit. Here is my conversion steps: 
1. HDR non-linear RGB to linear RGB (with PQ EOTF transfer function)
2. hable tone mapping (HDR-tools function rewrited by python)
3. color space conversion (with rec2020 to rec709 matrix in ITU.2047)
4. SDR linear RGB to non_linear RGB (with gamma 2.4)

I don not know where make mistakes, and cannot get the same conversion as ffmpeg. It will be appreciated if you tell me the reason for the mis-tranform.

**Comment by banterle** [comment]
Thank you for your message.

 #cannot get the same conversion as ffmpeg
I do not know what FFmpeg does so I cannot really help you with this.
The only strange thing that I see is that you use REC709 at step 3
and then you should use sRGB EOTF instead of just applying gamma 2.4.

What's the hable tone mapping?
